
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://pipelinepostgresdb.postgres.database.azure.com:5432/userdb?sslmode=require
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # use 'create' only if you want to reset DB on startup
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: ${JWT_SECRET:mysupersecretkeymysupersecretkey}
  expiration: ${JWT_EXPIRATION:3600000}


server:
  port: 8080
