apiVersion: v1
kind: Secret
metadata:
  name: user-service-secrets
type: Opaque
data:
  DB_USERNAME: YWRtaW51c2VyQHNvdXZmeWFucGlwZWxpbmVwb3N0Z3Jlc2Ri
  DB_PASSWORD: UGFzc3dvcmQxMjM=
  JWT_SECRET: UjBZZ0dneHVNM1ZsR0dWaU41VHFGRWdOcVlXUmZGQW9ja0lnWXpnPQ==
  DB_URL: amRiYzpwb3N0Z3JlczovL3NvdXZmeWFucGlwZWxpbmVwb3N0Z3Jlc2Qu
