apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  DB_HOST: cGlwZWxpbmVwb3N0Z3Jlc2RiLnBvc3RncmVzLmRhdGFiYXNlLmF6dXJlLmNvbQ==
  DB_PORT: NTQzMg==
  DB_NAME: dXNlcmRi
  DB_USERNAME: YWRtaW51c2VyQHBpcGVsaW5lcG9zdGdyZXNkYg==
  DB_PASSWORD: UGFzc3dvcmQxMjM=
  JWT_SECRET: bXlTZWNyZXRLZXlGb3JKV1RUb2tlbkdlbmVyYXRpb25BbmRWYWxpZGF0aW9uMTIzNDU2Nzg5MA==
