apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  DB_HOST: pipelinepostgresdb.postgres.database.azure.com
  DB_PORT: "5432"
  DB_NAME: userdb
  DB_USERNAME: adminuser@pipelinepostgresdb
  DB_PASSWORD: UGFzc3dvcmQxMjM=
  JWT_SECRET: bXlTZWNyZXRLZXlGb3JKV1RUb2tlbkdlbmVyYXRpb25BbmRWYWxpZGF0aW9uMTIzNDU2Nzg5MA==



  
